import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Goup from '../components/Goup'
import Intro from '../components/Intro'
import Navbar from '../components/Navbar'
import Skill from '../components/Skill'
import Work from '../components/Work'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Intro/>
      <About/>
      <Work/>
      <Skill/>
      <Contact/>
      <Footer/>
      <Goup />
    </div>
  )
}
